title = "出涸らし"
baseURL = "https://vstheworld.netlify.app"
languageCode = "ja"
theme = "gohugo-theme-ananke"
resourceDir = "../resources"

DefaultContentLanguage = "ja"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.ja]
    title = "出涸らし"
    weight = 1
    contentDir = "content"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/__vstheworld"
  instagram = "https://instagram.com/__vstheworld"
  youtube = ""
  github = "https://github.com/vstheworld"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  # featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  featured_image = "/images/header.jpg"
  recent_posts_number = 2

  mainSections = ["posts"]

# [menu]
# [[menu.main]]
# identifiler = "posts"
# name = "Posts"
# url = "/posts/"
# [[menu.main]]
# identifiler = "about"
# name = "About"
# url = "/posts/"